format = """
[](fg:#a3aed2)\
$os\
$username\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#212736 bg:#1d2230)\
$time\
[](fg:#1d2230)\
\n$character"""

# ---------- USERNAME ----------
[username]
show_always = true
style_user = "fg:#e3e5e5 bg:#769ff0"
format = '[ $user ]($style)'

# ---------- DIRECTORY ----------
[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

# ---------- GIT ----------
[git_branch]
symbol = ""
style = "fg:#769ff0 bg:#394260"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#769ff0 bg:#394260"
format = '[ $all_status$ahead_behind ]($style)'

# ---------- NODEJS ----------
[nodejs]
symbol = ""
style = "fg:#769ff0 bg:#212736"
format = '[ $symbol ($version) ]($style)'

# ---------- RUST ----------
[rust]
symbol = ""
style = "fg:#769ff0 bg:#212736"
format = '[ $symbol ($version) ]($style)'

# ---------- GOLANG ----------
[golang]
symbol = ""
style = "fg:#769ff0 bg:#212736"
format = '[ $symbol ($version) ]($style)'

# ---------- PHP ----------
[php]
symbol = ""
style = "fg:#769ff0 bg:#212736"
format = '[ $symbol ($version) ]($style)'

# ---------- TIME ----------
[time]
disabled = false
time_format = "%R"
style = "fg:#a0a9cb bg:#1d2230"
format = '[  $time ]($style)'

# ---------- OS ----------
[os]
disabled = false
style = "fg:#181818 bg:#a3aed2"  # gris oscuro con contraste
format = '[ $symbol ]($style)'

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

# ---------- CHARACTER ----------
[character]
success_symbol = '[❯](bold fg:#89ddff)'
error_symbol = '[❯](bold fg:#f07178)'

