import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
decorations = "Buttonless"
opacity = 0.5
blur = true
startup_mode= "Fullscreen"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

